services:
  playwright-tests:
    user: root
    build:
      context: .
      dockerfile: Dockerfile
      args:
        ENVIRONMENT: ${ENVIRONMENT:-dev}
    container_name: playwright-tests

    environment:
      ENVIRONMENT: ${ENVIRONMENT:-dev}

    env_file:
      - ./env1/.env.${ENVIRONMENT:-dev}

    volumes:
      - ./:/work
      - /work/node_modules
      - ./playwright-report:/work/playwright-report
      - ./test-results:/work/test-results
      - ./allure-results:/work/allure-results
      - ./allure-report:/work/allure-report
      - ./reports:/work/reports


    working_dir: /work
    shm_size: "2gb"

    command: >
      sh -c ""mkdir -p /work/reports/${ENVIRONMENT} &&
             chmod -R 777 /work/reports && echo 'Running in ${ENVIRONMENT:-dev} environment' &&
             npx playwright test"
