services:
  playwright-tests:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        ENVIRONMENT: ${ENVIRONMENT:-dev}
    container_name: playwright-tests

    environment:
      ENVIRONMENT: ${ENVIRONMENT:-dev}

    env_file:
      - ./env1/.env.${ENVIRONMENT:-dev}

    volumes:
      - ./:/work
      - /work/node_modules
      - ./test-results:/work/test-results
      - ./allure-results:/work/allure-results
      - ./allure-report:/work/allure-report

    working_dir: /work
    shm_size: "2gb"

    command: >
      sh -c "echo 'Running in ${ENVIRONMENT:-dev} environment' &&
             npx playwright test"
